CREATE TABLE [baseline].[WorkloadDetails] (
    [interval_id]     INT    NOT NULL,
    [sql_hash]        BIGINT NULL,
    [application_id]  INT    NOT NULL,
    [database_id]     INT    NOT NULL,
    [host_id]         INT    NOT NULL,
    [login_id]        INT    NOT NULL,
    [avg_cpu_ms]      INT    NULL,
    [min_cpu_ms]      INT    NULL,
    [max_cpu_ms]      INT    NULL,
    [sum_cpu_ms]      INT    NULL,
    [avg_reads]       INT    NULL,
    [min_reads]       INT    NULL,
    [max_reads]       INT    NULL,
    [sum_reads]       INT    NULL,
    [avg_writes]      INT    NULL,
    [min_writes]      INT    NULL,
    [max_writes]      INT    NULL,
    [sum_writes]      INT    NULL,
    [avg_duration_ms] INT    NULL,
    [min_duration_ms] INT    NULL,
    [max_duration_ms] INT    NULL,
    [sum_duration_ms] INT    NULL,
    [execution_count] INT    NULL
);

