

CREATE VIEW [dbo].[WorkloadOverView]
AS
SELECT interval_id, 
	end_time, 
	duration_minutes,
	sql_hash,
	example_text,
	normalized_text,
	application_name,
	database_name, 
	host_name, 
	login_name,
	AVG(avg_duration_ms) AS avg_duration_ms,
	MIN(min_duration_ms) AS min_duration_ms,
	MAX(max_duration_ms) AS max_duration_ms,
	SUM(sum_duration_ms) AS sum_duration_ms,
	AVG(avg_cpu_ms) AS avg_cpu_ms,
	MIN(min_cpu_ms) AS min_cpu_ms,
	MAX(max_cpu_ms) AS max_cpu_ms,
	SUM(sum_cpu_ms) AS sum_cpu_ms,
	AVG(avg_reads) AS avg_reads,
	MIN(min_reads) AS min_reads,
	MAX(max_reads) AS max_reads,
	SUM(sum_reads) AS sum_reads,
	AVG(avg_writes) AS avg_writes,
	MIN(min_writes) AS min_writes,
	MAX(max_writes) AS max_writes,
	SUM(sum_writes) AS sum_writes,
	SUM(execution_count) AS execution_count,

	AVG(avg_duration_ms2) AS avg_duration_ms2,
	MIN(min_duration_ms2) AS min_duration_ms2,
	MAX(max_duration_ms2) AS max_duration_ms2,
	SUM(sum_duration_ms2) AS sum_duration_ms2,
	SUM(execution_count2) AS execution_count2,
	AVG(avg_cpu_ms2) AS avg_cpu_ms2,
	MIN(min_cpu_ms2) AS min_cpu_ms2,
	MAX(max_cpu_ms2) AS max_cpu_ms2,
	SUM(sum_cpu_ms2) AS sum_cpu_ms2,
	AVG(avg_reads2) AS avg_reads2,
	MIN(min_reads2) AS min_reads2,
	MAX(max_reads2) AS max_reads2,
	SUM(sum_reads2) AS sum_reads2,
	AVG(avg_writes2) AS avg_writes2,
	MIN(min_writes2) AS min_writes2,
	MAX(max_writes2) AS max_writes2,
	SUM(sum_writes2) AS sum_writes2
FROM AllCorrelatedData
GROUP BY 
	interval_id, 
	end_time, 
	duration_minutes,
	sql_hash,
	example_text,
	normalized_text,
	application_name,
	database_name, 
	host_name, 
	login_name