<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
   <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="DouglasCrockford.JsMin" Version="1.1.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetFramework" Version="1.0.119.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.9.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.9.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.9.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.9.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WorkloadTools\WorkloadTools.csproj" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
</Project>